### ISSUE TITLE
New Function request

### ISSUE THREAD

**Issue by karlotroiano** [savoirfairelinux/redmine-issue-status-auto-open#2]
Hi,

is it possible to introduce the ability to choose on what tracker this "auto open plugin" works or not?

Thanks!
C.

**Comment by ghost** [comment]
I just finished implementing at the moment ! You can get the update from the master branch.
Ref commit : https://github.com/savoirfairelinux/redmine-issue-status-auto-open/commit/839bab84010c8814f905c6c7ff5f3490b95224ae

Have a great day !
